image: registry.obvsg.at:443/container/docker/saxon/xspec:debian-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - build
  - docs
  - deploy

compile:
  stage: build
  script:
    - mkdir dist
    - mkdir temp
    - mkdir -p test/xspec
    - saxon -xsl:xslt-bundler/xslt-builder.xsl -it:main configFile=../config.xml
    - bash temp/testrunner.sh
  artifacts:
    when: always
    name: package
    expire_in: 30 days
    paths:
      - dist/*
      - test/*
    reports:
      junit: test/xspec/*junit.xml

docs:
  stage: docs
  script:
    - mkdir docs
    - saxon-xslt -xsl:xslt-documentation-generator/xslt/documentation-generator.xsl -it:main lang=ger configFile=../../config.xml
  artifacts:
    paths:
      - docs

deploy_development:
  stage: deploy
  environment:
    name: development
    url: http://share-test.obvsg.at/docs/xslt-normalization
  before_script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    ##
    - 'apt-get update -y && apt-get install rsync -y'
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Give the right permissions, otherwise ssh-add will refuse to add files
    ## Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
    ##
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    ##
    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - rsync -r -p docs/* obvsoft@galileo:/work/obvsoft/evol/apps/work_area/ss/docs/xslt-normalization
  only:
    - development


deploy_main:
  stage: deploy
  environment:
    name: main
    url: http://share.obvsg.at/docs/xslt-normalization
  before_script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    ##
    - 'apt-get update -y && apt-get install rsync -y'
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Give the right permissions, otherwise ssh-add will refuse to add files
    ## Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
    ##
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    ##
    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - rsync -r -p docs/* obvsoft@obelix:/var/www/vhosts/share.obvsg.at/htdocs/xsldocs/xslt-normalization

  only:
    - main
